"""Render an optimized layout template as a C++ header."""

from __future__ import annotations

from struct_layout_optimizer import (
    OptimizationConfig,
    OptimizationOutcome,
    Type,
    Union,
    _ArrayTemplate,
    _AtomTemplate,
    _StructTemplate,
    _UnionTemplate,
    comparison_from_outcome,
    solve_layout,
)


def _line(level: int, text: str) -> str:
    return "    " * level + text


def _declaration(template, name: str, level: int, suffix: str = "") -> list[str]:
    if isinstance(template, _AtomTemplate):
        type_ = template.type
        return [_line(level, f"uint{type_.bits} {name}{suffix};")]

    if isinstance(template, _ArrayTemplate):
        return _declaration(
            template.element,
            name,
            level,
            f"[{template.array.count}]{suffix}",
        )

    if isinstance(template, _StructTemplate):
        lines = [_line(level, "struct {")]
        lines.extend(_struct_body(template, level + 1))
        lines.append(_line(level, f"}} {name}{suffix};"))
        return lines

    if isinstance(template, _UnionTemplate):
        lines = [_line(level, "union {")]
        for field, child in zip(template.union.members, template.members):
            lines.extend(_declaration(child, field.name, level + 1))
        lines.append(_line(level, f"}} {name}{suffix};"))
        return lines

    raise TypeError(template)


def _struct_body(template: _StructTemplate, level: int) -> list[str]:
    lines: list[str] = []
    fragment = 0
    for position, (field_index, child) in enumerate(zip(template.order, template.children)):
        gap = template.gaps[position]
        if gap:
            lines.append(_line(level, f"uint{gap} rsvd_{fragment};"))
            fragment += 1
        field = template.struct.fields[field_index]
        lines.extend(_declaration(child, field.name, level))
    trailing = template.gaps[-1]
    if trailing:
        lines.append(_line(level, f"uint{trailing} rsvd_{fragment};"))
    return lines


def render_optimized_header(
    type_: Type,
    start: int = 0,
    config: OptimizationConfig | None = None,
    outcome: OptimizationOutcome | None = None,
) -> str:
    """Return a self-contained declaration for the selected optimized layout.

    Nested composites are emitted as anonymous inline struct/union declarations
    so every chosen nested layout is represented exactly, including arrays.
    """
    config = config or OptimizationConfig()
    outcome = outcome or solve_layout(type_, start, config)
    template = outcome.template
    comparison = comparison_from_outcome(type_, outcome, start)
    name = getattr(type_, "name", "OptimizedLayout")
    kind = "union" if isinstance(type_, Union) else "struct"
    before = comparison.original.cost
    after = comparison.optimized.cost
    lines = [
        "#pragma once",
        "",
        "// Generated by struct-layout-optimizer.",
        f"// Search mode: {comparison.mode}",
        f"// Globally optimal: {'yes' if comparison.optimality_guaranteed else 'no'}",
        f"// Size: {comparison.optimized.size_bits} bit (unchanged)",
        f"// 32-bit crossings: {before.cross32} -> {after.cross32}",
        f"// 8-bit crossings: {before.cross8} -> {after.cross8}",
        "// BYTE crossings are counted only for fields narrower than 8 bit.",
        "",
    ]
    if isinstance(template, _StructTemplate):
        lines.append(f"{kind} {name} {{")
        lines.extend(_struct_body(template, 1))
        lines.append("};")
    elif isinstance(template, _UnionTemplate):
        lines.append(f"union {name} {{")
        for field, child in zip(template.union.members, template.members):
            lines.extend(_declaration(child, field.name, 1))
        lines.append("};")
    else:
        lines.extend(_declaration(template, name, 0))
    return "\n".join(lines) + "\n"
